### ISSUE TITLE
运行biLSTM-CRF报错IndexError: index 31 is out of bounds for dimension 0 with size 23

### ISSUE THREAD

**Issue by 550952213** [CLUEbenchmark/CLUENER2020#79]
Traceback (most recent call last):
  File "run_lstm_crf.py", line 245, in <module>
    main()
  File "run_lstm_crf.py", line 233, in main
    hidden_size=args.hidden_size,device=args.device,label2id=args.label2id)
  File "/home/ljcdp/YYJ_Project/CLUENER/bilstm_crf_pytorch/model.py", line 29, in __init__
    self.crf = CRF(tagset_size=len(label2id), tag_dictionary=label2id, device=device)
  File "/home/ljcdp/YYJ_Project/CLUENER/bilstm_crf_pytorch/crf.py", line 41, in __init__
    self.transitions.detach()[self.tag_dictionary[self.START_TAG], :] = -10000
IndexError: index 31 is out of bounds for dimension 0 with size 23

**Comment by 550952213** [comment]
已解决记录一下：几行类别注释取消
